### ISSUE TITLE
Remove cross-env

### ISSUE THREAD

**Issue by Yzrsah** [pmndrs/react-three-next#25]
https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-shell

"A JavaScript implementation of a bash-like shell"
- Portable across systems
- Supports variables

```
touch .yarnrc.yml
yarn set version berry
yarn plugin import interactive-tools
```

`.yarnrc.yml`
```
enableGlobalCache: true

enableTelemetry: false

nmHoistingLimits: none

nodeLinker: node-modules

packageExtensions:
  "troika-three-text@*":
    peerDependencies:
      "three": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
#  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#    spec: "@yarnpkg/plugin-workspace-tools"

pnpMode: strict

preferInteractive: true

yarnPath: .yarn/releases/yarn-berry.cjs
```
